import type { GadgetSettings } from "gadget-server";

export const settings: GadgetSettings = {
  type: "gadget/settings/v1",
  frameworkVersion: "v1.4.0",
  plugins: {
    connections: {
      shopify: {
        apiVersion: "2025-07",
        enabledModels: [
          "shopifyCustomer",
          "shopifyFile",
          "shopifyFulfillment",
          "shopifyInventoryItem",
          "shopifyInventoryLevel",
          "shopifyInventoryQuantity",
          "shopifyLocation",
          "shopifyOrder",
          "shopifyOrderLineItem",
          "shopifyPriceList",
          "shopifyPriceListPrice",
          "shopifyProduct",
          "shopifyProductMedia",
          "shopifyProductOption",
          "shopifyProductVariant",
          "shopifyProductVariantMedia",
          "shopifyQuantityPriceBreak",
          "shopifyRefund",
        ],
        type: "partner",
        scopes: [
          "read_customer_events",
          "read_locations",
          "read_order_edits",
          "read_products",
          "unauthenticated_write_customers",
          "write_customers",
          "write_fulfillments",
          "write_orders",
          "write_shipping",
          "unauthenticated_read_customers",
          "read_customers",
          "read_fulfillments",
          "read_orders",
          "read_shipping",
          "read_product_listings",
          "read_inventory",
          "write_inventory",
        ],
        customerAuthenticationEnabled: false,
      },
    },
  },
};
