import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://casepilot.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    checkoutApiSupportedJSON: {
      type: "json",
      storageKey:
        "ModelField-DataModel-Shopify-Shop-__gadget_graphql_checkout_api_supported::FieldStorageEpoch-DataModel-Shopify-Shop-__gadget_graphql_checkout_api_supported-initial",
    },
  },
  shopify: {
    fields: [
      "address1",
      "address2",
      "alerts",
      "billingAddress",
      "checkoutApiSupported",
      "city",
      "countriesInShippingZones",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "currencyFormats",
      "customerAccounts",
      "customerAccountsV2",
      "customerEmail",
      "customers",
      "description",
      "domain",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "files",
      "finances",
      "fulfillments",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "inventoryItems",
      "inventoryLevels",
      "latitude",
      "locations",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderLineItems",
      "orderNumberFormatPrefix",
      "orderNumberFormatSuffix",
      "orders",
      "passwordEnabled",
      "phone",
      "plan",
      "planDisplayName",
      "planName",
      "planPublicDisplayName",
      "preLaunchEnabled",
      "priceList",
      "priceListPrice",
      "primaryLocale",
      "primaryLocation",
      "productMedia",
      "productOptions",
      "productVariantMedia",
      "productVariants",
      "products",
      "province",
      "provinceCode",
      "quantityPriceBreak",
      "refunds",
      "requiresExtraPaymentsAgreement",
      "resourceLimits",
      "richTextEdiorUrl",
      "setupRequired",
      "shipsToCountries",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyInventoryQuantity",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "taxesOffset",
      "timezone",
      "timezoneAbbreviation",
      "timezoneOffsetMinutes",
      "transactionalSmsDisabled",
      "unitSystem",
      "url",
      "weightUnit",
      "zipCode",
    ],
  },
};
